version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongodb
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/docker-node-mongo
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
